import React, { useState } from 'react';
import UserService from '../Services/UserService';
import { User } from '../Types';

export default function SingleUserComponent(){
  const [message, setMessage] = useState('');
  const [macAddress, setMacAddress] = useState('');
  const [email, setEmail] = useState('');
  const [studentNumber, setStudentNumber] = useState('');
  const [timeNeeded, setTimeNeeded] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (parseInt(timeNeeded) < 1) {
      alert('Days needed must be at least 1.');
      return;
    }

    const newUser: User = {
      macAddress,
      email,
      studentNumber,
      password: 'TOBECHANGED - Autogenerated', 
      timeNeeded: parseInt(timeNeeded),
      active: 1,
      description,
    };

    try {
      const response = await UserService.addUser(newUser);
      if (response.ok) {
        setMessage('✅ User added successfully!');
        // Reset form fields:
        setMacAddress('');
        setEmail('');
        setStudentNumber('');
        setTimeNeeded('');
        setDescription('');
      } else {
        setMessage('❌ Error adding user.');
      }
    } catch (error) {
      console.error(error);
      setMessage('❌ An error occurred while submitting.');
    }
  };

  return (
    <div className="flex flex-col items-center w-full space-y-3 bg-white rounded-lg shadow-md p-6">
      <form
        onSubmit={handleSubmit}
        className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4 w-full"
      >
        <h3 className="text-xl font-bold pb-4 col-span-full text-center">User registration</h3>

        {/* Left Column */}
        <div className="flex flex-col space-y-3">
          <label className="text-sm font-medium">Mac Address *</label>
          <input
            type="text"
            placeholder="XX:XX:XX:XX:XX:XX"
            value={macAddress}
            onChange={(e) => setMacAddress(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-4 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
            required
          />

          <label className="text-sm font-medium">Email</label>
          <input
            type="text"
            placeholder="XX.XX@XX.X"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-4 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
          />

          <label className="text-sm font-medium">Student Number</label>
          <input
            type="text"
            placeholder='X0000000'
            value={studentNumber}
            onChange={(e) => setStudentNumber(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-4 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
          />
        </div>

        {/* Right Column */}
        <div className="flex flex-col space-y-3">
          <label className="text-sm font-medium">Days Needed *</label>
          <input
            type="number"
            placeholder="7"
            value={timeNeeded}
            onChange={(e) => setTimeNeeded(e.target.value)}
            min={1}
            className="bg-gray-300 text-black rounded-lg px-4 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
            required
          />

          <label className="text-sm font-medium">Description</label>
          <textarea
            placeholder="..."
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-6 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
            rows={5}
          />
        </div>

        {/* Message Display */}
        {message && (
          <div className="mt-4 text-sm col-span-full text-center text-black px-4 rounded-md">
            {message}
          </div>
        )}

        {/* Submit Button - Full Width */}
        <div className="col-span-full flex justify-center mt-2">
          <button
            type="submit"
            className="bg-[#002757] text-white py-1 px-4 rounded-md text-sm"
          >
            Submit
          </button>
        </div>
      </form>
    </div>
  );
}



