import React, { useEffect, useState } from 'react';
import UserService from '../Services/UserService';
import { User } from '../Types';

export default function SingleUserComponent(){
  const [message, setMessage] = useState('');
  const [macAddress, setMacAddress] = useState('');
  const [email, setEmail] = useState('');
  const [studentNumber, setStudentNumber] = useState('');
  const [timeNeeded, setTimeNeeded] = useState('');
  const [description, setDescription] = useState('');

  const [rows, setRows] = useState(5);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (parseInt(timeNeeded) < 1) {
      alert('Days needed must be at least 1.');
      return;
    }

    const newUser: User = {
      macAddress,
      email,
      studentNumber,
      password: 'TOBECHANGED - Autogenerated', 
      timeNeeded: parseInt(timeNeeded),
      active: 1,
      description,
    };

    try {
      const response = await UserService.addUser(newUser);
      if (response.ok) {
        setMessage('✅ User added successfully!');
        // Reset form fields:
        setMacAddress('');
        setEmail('');
        setStudentNumber('');
        setTimeNeeded('');
        setDescription('');
      } else {
        setMessage('❌ Error adding user.');
      }
    } catch (error) {
      console.error(error);
      setMessage('❌ An error occurred while submitting.');
    }
  };

  useEffect(() => {
    function handleResize() {
      if (window.innerWidth <= 768) { // md breakpoint in Tailwind is 768px
        setRows(3); // smaller rows on md and below
      } else {
        setRows(5); // default rows on larger screens
      }
    }
    
    handleResize(); // run on mount
    window.addEventListener("resize", handleResize);
    
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <div className="flex flex-col items-center w-full space-y-3 bg-white rounded-lg shadow-md p-6">
      <form
        onSubmit={handleSubmit}
        className="grid grid-cols-2 gap-x-8 gap-y-4 w-full form-grid-collapse"
      >
        <h3 className="text-xl font-bold pb-2 col-span-full text-center">User registration</h3>

        {/* Left Column */}
        <div className="flex flex-col space-y-3">
          <label className="text-sm font-medium">Mac Address *</label>
          <input
            type="text"
            placeholder="XX:XX:XX:XX:XX:XX"
            value={macAddress}
            onChange={(e) => setMacAddress(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-3 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
            required
          />

          <label className="text-sm font-medium">Email</label>
          <input
            type="text"
            placeholder="XX.XX@XX.X"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-3 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
          />

          <label className="text-sm font-medium">Student Number</label>
          <input
            type="text"
            placeholder='X0000000'
            value={studentNumber}
            onChange={(e) => setStudentNumber(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-3 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
          />
        </div>

        {/* Right Column */}
        <div className="flex flex-col space-y-3">
          <label className="text-sm font-medium">Days Needed *</label>
          <input
            type="number"
            placeholder="7"
            value={timeNeeded}
            onChange={(e) => setTimeNeeded(e.target.value)}
            min={1}
            className="bg-gray-300 text-black rounded-lg px-3 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300"
            required
          />

          <label className="text-sm font-medium">Description</label>
          <textarea
            placeholder="..."
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="bg-gray-300 text-black rounded-lg px-3 py-2 text-sm shadow-inner focus:outline-none focus:ring-2 focus:ring-blue-300 resize-none"
            rows={rows}
          />
        </div>

        {/* Message Display */}
        {message && (
          <div className="text-sm col-span-full text-center text-black px-4 rounded-md">
            {message}
          </div>
        )}

        {/* Submit Button - Full Width */}
        <div className="col-span-full flex justify-center">
          <button
            type="submit"
            className="bg-[#002757] text-white py-1 px-4 rounded-md text-sm"
          >
            Submit
          </button>
        </div>
      </form>
    </div>
  );
}



